let suggestions = [
    "Rome",
    "San Francisco",
    "Praga",
    "Varsovia",
    "Buenos Aires",
    "Bariloche",
    "Berlin",
    "Podgorica",
    "Kotor",
    "Tokio",
    "Lisboa",
    "Londres",
    "Estocolmo",
    "Auckland",
    "Miami",
    "Hawaii",
    "Napoli",
    "Zagreb",
    "Melbourne",
    "Bangkok",
    "Valencia",
    "Brujas",
    "Estambul",
    "El Cairo",
    "Dublin",
    "Glasgow",
];